// src/pages/about.tsx
import { type NextPage } from "next";
import Head from "next/head";
import LayoutBase from "~/components/LayoutBase";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Crystal Dashboard</title>
        <meta
          name="description"
          content="Your allround-helper for solving Pokémon Crystal"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutBase>
        <h1 className="mb-3 text-3xl font-semibold">About</h1>
        <p className="mb-3 dark:text-gray-300">
          This is a website with a configurable dashboard and a toolkit for
          helping you reaching different goals in Pokémon Crystal.
        </p>
        <p className="mb-3 dark:text-gray-300">
          This website does not track any user-specific data nor does it have a
          commercial purpose.
        </p>
        <p className="dark:text-gray-300">
          For bug reports, feature requests or feedback of any kind feel free to
          DM me on Discord: <strong>Froxx#7674</strong>
        </p>
      </LayoutBase>
    </>
  );
};

export default About;

// pages/about.vue
<template>
  <div>
    <h1>About</h1>
    <section id="about">
      <b-row>
        <b-col>
          <b-card>
            <b-card-text>
              This is a website with a configurable dashboard and a toolkit for
              helping you reaching different goals in Pokémon
              Crystal.</b-card-text
            >
            <b-card-text
              >This website does not track any user-specific data nor does it
              have a commercial purpose.</b-card-text
            >
            <b-card-text
              >For bug reports, feature requests or feedback of any kind feel
              free to DM me on Discord: <strong>Froxx#7674</strong></b-card-text
            >
          </b-card>
        </b-col>
      </b-row>
    </section>
  </div>
</template>
